import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./compiled.css";
import TopNav from '@/app/ui/topnav';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HisHerHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full bg-white adf" lang="en">
      <body style={{backgroundColor: "white"}} className={inter.className } >
      <div className="alm">
        <div>
              <TopNav />
              <main className="arq">
                <div className="arh cez dde">
                <div className="ab ph adf adx afw bbd">
                  {children}
                  </div>
                </div>
              </main>
        </div>
      </div>
      </body>
    </html>
  );
}

