import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from '@/app/ui/navbar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HisHerHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full bg-white" lang="en">
      <body style={{backgroundColor: "white"}} className={inter.className} ><NavBar />
      {children}
      </body>
    </html>
  );
}
