export const servicescheckbox = [
    {name: "b_services[]", value: "1-1 classes"},
    {name: "b_services[]", value: "Custom colouring"},
    {name: "b_services[]", value: "Custom wigs"},
    {name: "b_services[]", value: "Pre-made units"},
    {name: "b_services[]", value: "Natural hair maintenance"},
    {name: "b_services[]", value: "Ponytails"},
    {name: "b_services[]", value: "Sewins"},
    {name: "b_services[]", value: "Hair wash"},
    {name: "b_services[]", value: "Relaxer"},
    {name: "b_services[]", value: "Lace frontal wig"},
    {name: "b_services[]", value: "Lace closure"},
    {name: "b_services[]", value: "Shape ups"},
    {name: "b_services[]", value: "Skin fade"},
    {name: "b_services[]", value: "Trim"},
    {name: "b_services[]", value: "Beard shaping"},
    {name: "b_services[]", value: "Waves"},
    {name: "b_services[]", value: "Braids"},
    {name: "b_services[]", value: "Wash and go"},
    {name: "b_services[]", value: "Dreadlocks"},
    {name: "b_services[]", value: "Mobile hair services"},
    {name: "b_services[]", value: "Weddings"},
    {name: "b_services[]", value: "Photoshoots"},
    {name: "b_services[]", value: "Prom"},
    {name: "b_services[]", value: "Grooming"}
];